name: cameleon
version: 0.3.0
author:
  PLATEL Kevin <platel.kevin@gmail.com>
description:
  Library that provide simple way of creating http based application
homepage: https://github.com/platelk/cameleon.dart